# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datatrans', '0002_auto_20151221_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyvalue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='language',
            field=models.CharField(choices=[('it', 'Italiano'), ('en', 'English'), ('es', 'Espanol')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
