# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datatrans', '0003_auto_20171110_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
